export const data = [
    {
        'image':'angular-4-mini-logo-1.jpg',
        'name':'angular'
    },
    {
        'image':'reactjs-mini-logo.jpg',
        'name':'react'
    },
    {
        'image':'html5-mini-logo.jpg',
        'name':'html5'
    },
    {
        'image':'bootstrap-mini-logo.jpg',
        'name':'bootstrap'
    },
    {
        'image':'jasmine-js-mini-logo.jpg',
        'name':'jasmine'
    },
    {
        'image':'javascript-mini-logo.jpg',
        'name':'javascript'
    },
    {
        'image':'less-mini-logo.jpg',
        'name':'less'
    },
    {
        'image':'sass-mini-logo.jpg',
        'name':'sass'
    },
    {
        'image':'typescript-mini-logo.jpg',
        'name':'typescript'
    },
    
    {
        'image':'nodejs-mini-logo.jpg',
        'name':'nodejs'
    },
    {
        'image':'mongodb-mini-logo.jpg',
        'name':'mongodb'
    },
    {
        'image':'jquery-mini-logo.jpg',
        'name':'jquery'
    },
]
